### ISSUE TITLE
[www] Tagline

### ISSUE THREAD

**Issue by thuey** [pleaseops/www#28]
PleaseOps: Because configuring every tool, for every environment, for every machine is an ops nightmare.

**Comment by thuey** [comment]
@jonnymbgood Thoughts?

**Comment by jonnymbgood** [comment]
@thuey Just spitballing.

Because properly provisioning every developer's machine to access every tool, and every infrastructure [provider] to allow each developer access, and keeping every link to every tool on every machine is a pain.

Because keeping every tool on every developers machine secure and up-to-date sucks

Because keeping every developer's machine properly provisioned with the right tools on the right versions with the proper permissions sucks

Because keeping everyone's machine synchronized with the right tools on the right versions with the right infrastructure permissions sucks.

Because provisioning every machine with the right combination of tooling, versions, links, and infrastructure access sucks.

Because keeping everyone's machines on the right version of the right tool with the right links with the right infrastructure access sucks.

Because keeping everyone's machines on the right version of the tools with the right infrastructure access sucks.

Because keeping the tools, access, and links on everyone's machines in sync sucks.

Because keeping the [....] tools, correct access, and current links on everyone's machine sucks.

Because keeping the right version of the right tool configured with the right access and pointing at the right thing to properly do devops is a nightmare

Because keeping the correct version of the correct tool configured with the correct access and pointing at the correct location to properly do devops is a nightmare

Because devops means keeping correct version of the correct tool configured with the correct access and pointing at the correct location on EVERYONE's machine.

DevOps: having the correct version of the correct tool configured with the correct access to properly respond to an outage.

Because having the correct version of the correct tool configured with the correct access to properly respond to an outage on every machine sucks

Because having the correct version of the correct tool with the correct access to properly respond to an outage on every machine sucks

Because having the current version of the proper software with the correct access to properly respond in an outage on everyone's machine sucks

Because giving everyone the current version of the right software with the correct access to properly respond in an outage sucks

Because giving everyone the right version of the [necessary] software with the correct access to properly respond in an outage sucks

[right software, right version, right access, right knowledge == successful outage response || good devops development]

**Comment by jonnymbgood** [comment]
Because giving everyone the right version of the required software with the correct access to properly do DevOps sucks

Because provisioning everyone with the right version of the required software with the correct access to properly do DevOps, sucks

**Comment by jonnymbgood** [comment]
Because giving everyone the right version of the requisite software with the correct access to properly respond in an outage sucks

**Comment by thuey** [comment]
Because only the DevOps machines should be provisioned like DevOps machines.

Because accessing infrastructure should be fast, painless, and secure.

Because you need a bigger bus factor.

**Comment by thuey** [comment]
Because DevOps needed to be DevOps-ed.

**Comment by thuey** [comment]
Closing this issue. I think it will be best to have this conversation in person, but we can use this as a reference.
