### ISSUE TITLE
[www] PleaseOps tagline

### ISSUE THREAD

**Issue by thuey** [pleaseops/www#7]
@jonnymbgood Here is the description of PleaseOps to get the conversation and wordsmithing going:

PleaseOps is a DevSecOps tool for managing access control and triaging infrastructure without the need to provision permissions for everyone.

**Comment by jonnymbgood** [comment]
@thuey Pong

PleaseOps - A chatops tool for managing infrastructure and operations [access/tooling], allowing on the spot triage and access for your organization directly in chat.

**Important points**:
* ChatOps/access from a public place where people can see the commands/manage the tool
* Manage access without managing access in each tool directly
* Pulls information into chat rather than everyone going out to get it
* Shows triage information directly in the incident channel and helps keep everyone on the same page

**Other points/thoughts**:
* Saves time in an incident
* Easy to onboard/offboard
* Most devs don't have to install a gazillion tools (but they can if they are power users)
* Don't have to manage local versions of tooling for each dev
* Manages permissions as granular as you want to
* Diagnose issues without having to remember 15 commands (just 1 or 2), and without having to be an expert (do normal devs think to look for low disk space or scan the events in their namespace when confronted by an issue?)

**Comment by thuey** [comment]
Feedback on your tagline:
- A chatops tool: Cool, I was unfamiliar with the term "chatops"
- for managing infrastructure and operations [access/tooling]: How much "managing" do you think there will be? Managing seems to imply "writing" but we haven't talked much about writing.
- allowing on the spot triage and access for your organization directly in chat: This feels a bit verbose. I think it could be simplified to something like "allowing triage and access for your team."

As I think about it more, there are two things we've talked about that we don't seem to have much in the roadmap for: access and managing. I know we have access with AWS. But will there be anything else we can generate access links to? Would it possibly make sense to focus on the triage aspect and access is almost an extension of triaging?

PleaseOps - A chatops tool that allows your team to collaboratively triage your infrastructure without compromising security.

**Comment by jonnymbgood** [comment]
* chatops - really seemed to take off with hubot at Github: https://speakerdeck.com/jnewland/chatops-at-github
* Management may be the wrong/not best word here. So in my head we are managing access to the underlying tools through PleaseOps directly (via grant/revoke). In a perfect world you would only need to use pleaseops to do your day to day job and not have to worry about having kubectl, aws cli, nslookup, etc... installed and configured correctly on everyone's machines. Plus you don't have to manage the access permissions for each of those tools within the tool itself (RBAC and revoking dev permissions)
* Yup

IMO PleaseOps won't be nearly as effectively unless it has the capabilities to be a part of every day life in a company (please login/deploy/get/check/describe/merge/build/spinup/find/...). Also, if a tool is only used for triage and not day to day then most people won't know about it or how to use it. But if the tool you use everyday also does triage, then you know how to interact with it and know how to use it. It only seems to work in my mind if the tool you use everyday also helps in a crisis vs. having a crisis tool that you don't use everyday.

**Comment by thuey** [comment]
PleaseOps - A chatops tool that enables team members to safely access infrastructure and manage operations.

From this take, triage is now an extension on and feature of access and management, instead of the other way around like I was proposing. It feels much better. I'm glad you pushed back.

We could tack on something like "...from your favorite chat application," but that feels redundant, since we started off by pointing out it's a "chatops tool."

**Comment by jonnymbgood** [comment]
Or we could drop the chatops part and go with `Safely access infrastructure and manage operations, all through your favorite chat application.`

Or `Access infrastructure, manage operations, and triage issues, all through your favorite chat application.` Did our main 3 uses just pop out?

I'm thinking we should lean more towards a very clear "what is PleaseOps" for the main tagline, even if it means being a little dry.

Thoughts?

**Comment by jonnymbgood** [comment]
closed via #14
